<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WebApplication6.Default" %>


<!DOCTYPE html>

<html>
<head>
  <title>Course Instances</title>
</head>

<script runat="server">
  void Page_Load(object sender, EventArgs e)
  {
    Welcome.Text = "Please add new course including Code, Date and Trainer. All fiels are mandatory. Insert date in YYYY/MM/DD format only.";
  }

  void Signout_Click(object sender, EventArgs e)
  {
    FormsAuthentication.SignOut();
    Response.Redirect("Logon.aspx");
  }
</script>

    

<body>
  <h3>
    Welcome to Course Instance Page
  </h3>
  <asp:Label ID="Welcome" runat="server" />
  <form id="Form1" runat="server">
      <p>
          <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="Code,Date" Height="127px" Width="314px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
              <Columns>
                  <asp:BoundField DataField="Code" HeaderText="Code" ReadOnly="True" SortExpression="Code" />
                  <asp:BoundField DataField="Date" HeaderText="Date" ReadOnly="True" SortExpression="Date" />
                  <asp:BoundField DataField="Trainer" HeaderText="Trainer" SortExpression="Trainer" />
              </Columns>
          </asp:GridView>
          <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Database1ConnectionString %>" SelectCommand="SELECT [Code], [Date], [Trainer] FROM [CourseInstance]" UpdateCommand ="UPDATE [CourseInstance] Set [Code] = @code, [Date] = @date, [Trainer] = @trainer"></asp:SqlDataSource>
          <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
          <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
          <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
          <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Insert" />
      <p>
    <asp:Button ID="Submit1" OnClick="Signout_Click" 
       Text="Sign Out" runat="server" />
      </p>
  </form>
</body>
</html>